#pragma once

#define TEST_RUNNER_NAMESPACE            test_runner
#define BEGIN_TEST_RUNNER_NAMESPACE      namespace TEST_RUNNER_NAMESPACE {
#define END_TEST_RUNNER_NAMESPACE        }

#define USING_NAMESPACE_TEST_RUNNER      using namespace TEST_RUNNER_NAMESPACE;

BEGIN_TEST_RUNNER_NAMESPACE

END_TEST_RUNNER_NAMESPACE
