name: PlatformIO

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  platformio:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - examples/AltPinSerial
          - examples/Basic_IO
          - examples/Bench
          - examples/Callbacks
          - examples/DualMerger
          - examples/ErrorCallback
          - examples/Input
          - examples/RPN_NRPN
          - examples/SimpleSynth
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: >
        pio ci
        --verbose
        --lib="."
        --board="uno"
        --board="due"
        --board="zero"
        --board="leonardo"
        --board="micro"
        --board="nanoatmega328"
        --board="megaatmega2560"
        --board="teensy2"
        --board="teensy30"
        --board="teensy31"
        --board="teensylc"
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
